"""
app.py — JobGuard: AI-Powered Job Fraud Detection (v6)
============================================================================
Changes from v5:
  ✅ "Not a job posting" guard — rejects unrelated content before ML inference
  ✅ Heuristic confidence nudge REMOVED — no more fabricated confidence adjustments
  ✅ Threshold defaults to 0.5 with clear comment (threshold.json generated by train.py)
  ✅ Multi-worker safety: active model selection reads active_model.json per-request
     so gunicorn -w N works correctly (each worker sees the same selection)
  ✅ /select-model and /clear_history protected with a simple admin token check
  ✅ Rate limiter storage_uri documented — swap to redis:// for production clusters
"""

import os
import sys
import pickle
import logging
import sqlite3
import datetime
import math
import json
import time

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

from flask import (Flask, render_template, request,
                   redirect, url_for, jsonify, flash)

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from utils.preprocessing import preprocess
from utils.evaluation import (
    load_metrics,
    load_model_registry,
    load_model_by_name,
)
from utils.explainer import explain
from analyzer import analyse_all

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
logger = logging.getLogger(__name__)

app = Flask(__name__)
app.secret_key = os.environ.get("FLASK_SECRET_KEY")

if not app.secret_key:
    if os.environ.get("FLASK_ENV") == "production":
        raise RuntimeError(
            "FLASK_SECRET_KEY must be set in production. "
            "Generate one with: python -c \"import secrets; print(secrets.token_hex(32))\""
        )
    logger.warning(
        "FLASK_SECRET_KEY not set — using insecure dev default. "
        "Set it in .env or as an environment variable."
    )
    app.secret_key = "jobguard_dev_secret_not_for_production"

# ── Admin token for destructive routes (/select-model, /clear_history) ──
# Set ADMIN_TOKEN in .env. If unset in dev, a warning is shown and the routes
# require no auth (acceptable for local use only).
ADMIN_TOKEN = os.environ.get("ADMIN_TOKEN", "")

# ── Rate limiting ──────────────────────────────────────────────────────
try:
    from flask_limiter import Limiter
    from flask_limiter.util import get_remote_address
    # storage_uri="memory://" works for a single-process deployment.
    # For multi-worker (gunicorn -w N, N>1): set RATELIMIT_STORAGE_URI=redis://...
    _storage = os.environ.get("RATELIMIT_STORAGE_URI", "memory://")
    limiter = Limiter(
        get_remote_address,
        app=app,
        default_limits=["200 per day", "60 per hour"],
        storage_uri=_storage,
    )
    _limiter_available = True
except ImportError:
    logger.warning("Flask-Limiter not installed — API rate limiting disabled.")
    class _NoopLimiter:
        def limit(self, *a, **kw):
            def decorator(f): return f
            return decorator
    limiter = _NoopLimiter()

# ── Paths ──────────────────────────────────────────────────────────────
BASE_DIR    = os.path.dirname(os.path.abspath(__file__))
MODEL_PATH  = os.path.join(BASE_DIR, "models", "model.pkl")
VEC_PATH    = os.path.join(BASE_DIR, "models", "vectorizer.pkl")
MD_PATH     = os.path.join(BASE_DIR, "models", "model_metadata.json")
ACTIVE_PATH = os.path.join(BASE_DIR, "models", "active_model.json")
THRESH_PATH = os.path.join(BASE_DIR, "models", "threshold.json")
DB_PATH     = os.path.join(BASE_DIR, "data", "predictions.db")

MAX_TEXT_LEN = 20_000

# ── Job-posting vocabulary guard ──────────────────────────────────────
# Minimum number of job-related terms that must appear in the text before
# we run ML inference. This prevents unrelated content (blog posts, Wikipedia
# articles, product descriptions) from being classified as "Legitimate" simply
# because they contain no fraud vocabulary.
_JOB_TERMS = {
    "job", "role", "position", "vacancy", "opening", "hiring", "salary",
    "responsibilities", "requirements", "experience", "qualification",
    "candidate", "apply", "employer", "employee", "work", "company",
    "team", "office", "remote", "skills", "profile", "resume", "cv",
    "interview", "joining", "department", "designation", "ctc", "lpa",
    "fresher", "graduate", "engineer", "manager", "developer", "analyst",
    "internship", "full-time", "part-time", "contract", "permanent",
}
_JOB_TERM_THRESHOLD = 3   # at least 3 job terms must appear


def _is_job_posting(text: str) -> bool:
    """Return True if the text looks like a job posting, False otherwise."""
    words = set(text.lower().split())
    matches = words & _JOB_TERMS
    return len(matches) >= _JOB_TERM_THRESHOLD


# ── Classification threshold ───────────────────────────────────────────
# train.py writes models/threshold.json with the F1-optimal threshold.
# Falls back to 0.5 when the file is absent (e.g. before first training run).
_threshold = 0.5
if os.path.exists(THRESH_PATH):
    try:
        with open(THRESH_PATH) as f:
            _threshold = float(json.load(f).get("threshold", 0.5))
        logger.info(f"Loaded classification threshold: {_threshold:.2f}")
    except Exception:
        logger.warning("Could not parse threshold.json — using 0.5")

# ── Vectorizer (loaded once — shared across model switches) ───────────
try:
    with open(VEC_PATH, "rb") as f:
        vectorizer = pickle.load(f)
    logger.info("Vectorizer loaded.")
except FileNotFoundError:
    logger.warning("Vectorizer not found. Run train.py first.")
    vectorizer = None

# ── In-process model cache ────────────────────────────────────────────
# _model_cache holds the last-loaded model to avoid disk I/O on every
# request. The active model name is always read from active_model.json
# so all gunicorn workers stay in sync when the model is switched.
_model_cache: dict = {"name": None, "model": None}


def _get_active_model():
    """
    Return (name, model) for the currently selected model.

    Reads active_model.json on every call to stay multi-worker safe,
    but caches the loaded object so disk reads only happen on switches.
    """
    # Determine desired name from persisted selection
    desired_name = None
    if os.path.exists(ACTIVE_PATH):
        try:
            with open(ACTIVE_PATH) as f:
                desired_name = json.load(f).get("active_model")
        except Exception:
            pass

    # Fall back to best model if no selection persisted
    if not desired_name and os.path.exists(MD_PATH):
        try:
            with open(MD_PATH) as f:
                desired_name = json.load(f).get("best_model")
        except Exception:
            pass

    # Return cached model if name hasn't changed
    if desired_name and desired_name == _model_cache["name"]:
        return _model_cache["name"], _model_cache["model"]

    # Load from disk
    if desired_name:
        m = load_model_by_name(desired_name)
        if m:
            _model_cache["name"]  = desired_name
            _model_cache["model"] = m
            return desired_name, m

    # Final fallback: load model.pkl directly
    if os.path.exists(MODEL_PATH):
        try:
            with open(MODEL_PATH, "rb") as f:
                m = pickle.load(f)
            name = desired_name or "Best Model"
            _model_cache["name"]  = name
            _model_cache["model"] = m
            return name, m
        except Exception:
            pass

    return None, None


def _active_model_name() -> str:
    name, _ = _get_active_model()
    return name or "None"


def _switch_model(name: str) -> bool:
    """Persist model selection to active_model.json. Returns True on success."""
    m = load_model_by_name(name)
    if m is None:
        return False
    os.makedirs(os.path.dirname(ACTIVE_PATH), exist_ok=True)
    with open(ACTIVE_PATH, "w") as f:
        json.dump({"active_model": name, "switched_at": datetime.datetime.now().isoformat()}, f)
    # Update cache for this worker immediately
    _model_cache["name"]  = name
    _model_cache["model"] = m
    logger.info(f"Switched active model → {name}")
    return True


def _check_admin(req) -> bool:
    """Return True if the request carries a valid admin token (or no token is configured)."""
    if not ADMIN_TOKEN:
        return True   # dev mode — no token configured
    provided = req.form.get("admin_token", "").strip() or req.headers.get("X-Admin-Token", "").strip()
    return provided == ADMIN_TOKEN


def load_metadata() -> dict:
    if os.path.exists(MD_PATH):
        with open(MD_PATH) as f:
            return json.load(f)
    return {}


# ── ML prediction ──────────────────────────────────────────────────────

def ml_predict(combined: str, raw_for_explain: str = "") -> dict:
    """
    Run inference on combined text using the active model.
    Returns error dict if model/vectorizer not loaded.
    No heuristic confidence adjustments — confidence reflects the model only.
    """
    model_name, model = _get_active_model()
    if not model:
        return {"error": "Model not loaded. Run train.py first."}
    if not vectorizer:
        return {"error": "Vectorizer not loaded. Run train.py first."}

    combined = combined[:MAX_TEXT_LEN]
    cleaned  = preprocess(combined)
    vec      = vectorizer.transform([cleaned])

    if hasattr(model, "predict_proba"):
        prob_fraud = float(model.predict_proba(vec)[0][1])
        pred       = int(prob_fraud >= _threshold)
        conf       = round((prob_fraud if pred == 1 else 1 - prob_fraud) * 100, 2)
    elif hasattr(model, "decision_function"):
        s    = float(model.decision_function(vec)[0])
        pred = int(model.predict(vec)[0])
        conf = round((1 / (1 + math.exp(-abs(s)))) * 100, 2)
    else:
        pred = int(model.predict(vec)[0])
        conf = 95.0

    explain_input = (raw_for_explain or combined)[:MAX_TEXT_LEN]
    explanation   = explain(explain_input, vectorizer, model)

    return {
        "label":      "Fraudulent" if pred == 1 else "Legitimate",
        "confidence": conf,
        "is_fraud":   pred == 1,
        "model_name": model_name or explanation["model_name"],
        "explanation": explanation,
    }


# ── Database ───────────────────────────────────────────────────────────

def get_db():
    c = sqlite3.connect(DB_PATH)
    c.row_factory = sqlite3.Row
    return c


def init_db():
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    with get_db() as c:
        c.execute("""
            CREATE TABLE IF NOT EXISTS predictions (
                id           INTEGER PRIMARY KEY AUTOINCREMENT,
                job_title    TEXT,
                company      TEXT,
                location     TEXT,
                salary       TEXT,
                website      TEXT,
                description  TEXT NOT NULL,
                requirements TEXT,
                prediction   TEXT NOT NULL,
                confidence   REAL NOT NULL,
                url_risk     TEXT,
                url_score    REAL,
                model_used   TEXT,
                submitted_at DATETIME DEFAULT CURRENT_TIMESTAMP
            )""")
        for col_sql in [
            "ALTER TABLE predictions ADD COLUMN model_used TEXT",
            "ALTER TABLE predictions ADD COLUMN url_risk TEXT",
            "ALTER TABLE predictions ADD COLUMN url_score REAL",
        ]:
            try:
                c.execute(col_sql)
            except Exception:
                pass
        c.commit()


def save_pred(fd: dict, result: dict, url_risk: str = "low", url_score: float = 0):
    with get_db() as c:
        c.execute(
            "INSERT INTO predictions "
            "(job_title,company,location,salary,website,description,"
            " requirements,prediction,confidence,url_risk,url_score,model_used) "
            "VALUES (?,?,?,?,?,?,?,?,?,?,?,?)",
            (fd.get("job_title",""), fd.get("company",""), fd.get("location",""),
             fd.get("salary",""),    fd.get("website",""), fd.get("description",""),
             fd.get("requirements",""), result["label"], result["confidence"],
             url_risk, url_score, result.get("model_name","")))
        c.commit()


def get_history(limit: int = 100):
    with get_db() as c:
        return [dict(r) for r in c.execute(
            "SELECT * FROM predictions ORDER BY submitted_at DESC LIMIT ?",
            (limit,)).fetchall()]


def get_stats() -> dict:
    with get_db() as c:
        total = c.execute("SELECT COUNT(*) FROM predictions").fetchone()[0]
        fraud = c.execute(
            "SELECT COUNT(*) FROM predictions WHERE prediction='Fraudulent'"
        ).fetchone()[0]
    return {"total": total, "fraud": fraud, "legit": total - fraud}


# ── Routes ─────────────────────────────────────────────────────────────

@app.route("/")
def home():
    return render_template("index.html", stats=get_stats())


@app.route("/classify")
def classify():
    return render_template("classify.html", active_model=_active_model_name())


@app.route("/predict", methods=["POST"])
def predict_route():
    t0 = time.perf_counter()

    fd = {k: request.form.get(k, "").strip()
          for k in ["job_title", "company", "location",
                    "salary", "website", "description", "requirements"]}

    if not fd["description"]:
        flash("Job description is required.", "error")
        return render_template("classify.html", form=fd,
                               active_model=_active_model_name())

    if len(fd["description"]) > MAX_TEXT_LEN:
        fd["description"] = fd["description"][:MAX_TEXT_LEN]

    combined = " ".join(filter(None, [
        fd["job_title"], fd["company"], fd["description"], fd["requirements"]
    ]))

    # ── Job posting guard ──────────────────────────────────────────────
    if not _is_job_posting(combined):
        flash(
            "The text you entered does not appear to be a job posting. "
            "Please paste an actual job description.",
            "warning"
        )
        return render_template("classify.html", form=fd,
                               active_model=_active_model_name())

    raw_for_explain = " ".join(filter(None, [
        fd["job_title"], fd["company"], fd["description"],
        fd["requirements"], fd["salary"]
    ]))

    result = ml_predict(combined, raw_for_explain)
    if "error" in result:
        flash(result["error"], "error")
        return render_template("classify.html", form=fd,
                               active_model=_active_model_name())

    analysis = analyse_all(fd.get("website", ""), fd.get("company", ""))

    save_pred(fd, result, analysis["overall_risk"], analysis["url"]["score"])

    elapsed_ms = round((time.perf_counter() - t0) * 1000, 1)
    logger.info("Prediction: %s | conf=%.1f%% | %dms | model=%s",
                result["label"], result["confidence"], elapsed_ms,
                result.get("model_name", "?"))

    return render_template("result.html",
                           result=result,
                           job=fd,
                           analysis=analysis,
                           elapsed_ms=elapsed_ms)


@app.route("/history")
def history():
    return render_template("history.html",
                           history=get_history(), stats=get_stats())


@app.route("/about")
def about():
    return render_template("about.html", metadata=load_metadata())


@app.route("/models")
def models_page():
    return render_template("models.html",
                           metrics=load_metrics(),
                           metadata=load_metadata(),
                           active_model=_active_model_name(),
                           registry=load_model_registry())


@app.route("/clear_history", methods=["POST"])
def clear_history():
    if not _check_admin(request):
        flash("Unauthorized — provide a valid admin token.", "error")
        return redirect(url_for("history"))
    with get_db() as c:
        c.execute("DELETE FROM predictions")
        c.commit()
    flash("History cleared.", "success")
    return redirect(url_for("history"))


@app.route("/select-model", methods=["POST"])
def select_model():
    """
    Switch the active inference model. Persists selection to active_model.json
    so all gunicorn workers pick it up on their next request.
    Requires ADMIN_TOKEN if set in environment.
    """
    if not _check_admin(request):
        flash("Unauthorized — provide a valid admin token.", "error")
        return redirect(url_for("models_page"))

    name = request.form.get("model_name", "").strip()
    if not name:
        flash("No model name provided.", "error")
        return redirect(url_for("models_page"))

    if _switch_model(name):
        flash(f"Active model switched to: {name}", "success")
    else:
        flash(f"Model '{name}' not found in registry. Run train.py first.", "error")
    return redirect(url_for("models_page"))


# ── JSON API ───────────────────────────────────────────────────────────

@app.route("/api/predict", methods=["POST"])
@limiter.limit("30 per minute")
def api_predict():
    """
    JSON prediction API.

    Request body:
        title       : str (optional)
        company     : str (optional)
        description : str (REQUIRED)
        requirements: str (optional)
        website     : str (optional)
        model       : str (optional — per-request model override)
    """
    data = request.get_json(force=True, silent=True) or {}

    description = str(data.get("description", "")).strip()
    if not description:
        return jsonify({"error": "description is required"}), 400

    combined = " ".join(filter(None, [
        str(data.get("title", "")),
        str(data.get("company", "")),
        description,
        str(data.get("requirements", "")),
    ]))

    # Job posting guard
    if not _is_job_posting(combined):
        return jsonify({
            "error": "Input does not appear to be a job posting. "
                     "Please submit an actual job description."
        }), 422

    # Per-request model override (reads from registry, does NOT mutate cache)
    req_model_name = str(data.get("model", "")).strip()
    if req_model_name:
        override_model = load_model_by_name(req_model_name)
    else:
        override_model = None

    if override_model:
        # Temporarily use override without mutating the cache
        _, active = _get_active_model()
        active_name = _active_model_name()
        # Inline inference with override model
        import copy as _copy
        original_cache = dict(_model_cache)
        _model_cache["name"]  = req_model_name
        _model_cache["model"] = override_model
        result = ml_predict(combined, combined + " " + str(data.get("salary", "")))
        _model_cache.update(original_cache)
    else:
        result = ml_predict(combined, combined + " " + str(data.get("salary", "")))

    if "error" in result:
        return jsonify(result), 503

    analysis = analyse_all(
        str(data.get("website", "")),
        str(data.get("company", "")),
    )

    exp = result.get("explanation", {})
    return jsonify({
        "prediction":     result["label"],
        "is_fraud":       result["is_fraud"],
        "confidence":     result["confidence"],
        "model_used":     result.get("model_name", ""),
        "url_risk":       analysis["overall_risk"],
        "combined_score": analysis["combined_score"],
        "explanation": {
            "top_fraud_words": exp.get("top_fraud_words", []),
            "top_legit_words": exp.get("top_legit_words", []),
            "fraud_patterns": [
                {"label": p["label"], "severity": p["severity"],
                 "reason": p["reason"], "matched": p["matched"]}
                for p in exp.get("fraud_patterns", [])
            ],
            "reasons":        exp.get("reasons", []),
            "decision_score": exp.get("decision_score", 0),
        },
    })


@app.route("/api/models", methods=["GET"])
def api_models():
    registry    = load_model_registry()
    all_metrics = {m["name"]: m for m in load_metrics()}
    models_list = []
    for name, path in registry.items():
        entry = {
            "name":      name,
            "available": os.path.exists(path),
            "is_active": name == _active_model_name(),
        }
        if name in all_metrics:
            m = all_metrics[name]
            entry.update({
                "accuracy":        m.get("accuracy"),
                "f1_fraud":        m.get("f1_fraud"),
                "recall_fraud":    m.get("recall_fraud"),
                "precision_fraud": m.get("precision_fraud"),
                "roc_auc":         m.get("roc_auc"),
                "cv_f1_mean":      m.get("cv_f1_mean"),
                "cv_f1_std":       m.get("cv_f1_std"),
            })
        models_list.append(entry)
    return jsonify({"active_model": _active_model_name(), "models": models_list})


@app.route("/health")
def health():
    _, model = _get_active_model()
    return jsonify({
        "status":        "ok",
        "model_loaded":  model is not None,
        "active_model":  _active_model_name(),
        "vectorizer_ok": vectorizer is not None,
        "threshold":     _threshold,
        "timestamp":     datetime.datetime.now().isoformat(),
    })


# ── Error handlers ─────────────────────────────────────────────────────

@app.errorhandler(404)
def not_found(e):
    return render_template("404.html"), 404


@app.errorhandler(500)
def server_error(e):
    logger.error("500 error: %s", e)
    return render_template("500.html"), 500


# ══════════════════════════════════════════════════════════════════════
if __name__ == "__main__":
    init_db()
    debug = os.environ.get("FLASK_ENV") == "development"
    port  = int(os.environ.get("PORT", 5000))
    logger.info(f"JobGuard — http://localhost:{port}")
    app.run(debug=debug, host="0.0.0.0", port=port)
